### ISSUE TITLE
Should we kill the mailing list and move to slack?

### ISSUE THREAD

**Issue by dblock** [ruby-grape/ruby-grape.github.io#29]
The mailing list is annoying to say the least.

**Comment by mbleigh** [comment]
Mailing lists have the nicety of a searchable archive that surfaces in Google results and potentially prevents confusion. I'm happy with moving to Slack but there should be a wiki page or similar to capture anything that comes up on a regular basis.

**Comment by pswenson** [comment]
slack +1

**Comment by LeFnord** [comment]
hi @mbleigh, nice to met you :smile:

mmh, Slack is cool for a short way of communication/for discussions,
but a mailing list is better for a kind of documentation what is going on and, of course … searching

Slack is also searchable, but only for paid accounts,
and we can not and should not assume, that every body has one :wink:

**Comment by dblock** [comment]
I made a gitter room for now, that seems to strike a good balance. I'll hang out there from time to time.
https://gitter.im/ruby-grape/grape
