### ISSUE TITLE
Should Grape have a Twitter account?

### ISSUE THREAD

**Issue by dblock** [ruby-grape/ruby-grape.github.io#4]
ruby-grape is something cute on Twitter already

**Comment by towanda** [comment]
I think so, It would be nice to get tweets about new releases, changes, etc..

**Comment by dblock** [comment]
I'd like someone to step up as an owner of something like this and commit to spending a bit of time finding interesting grape things, (re)tweeting them, etc., If you're interested say "aye".

**Comment by towanda** [comment]
aye :smile:

**Comment by dblock** [comment]
@towanda I created a [grapeframework](https://twitter.com/grapeframework) account on Twitter, invited you to the [TweetDeck team](https://tweetdeck.twitter.com/), so you should be able to post to this account now.

Obviously we need to reference the account somewhere in ruby-grape.github.io, document how we post, tell the list to follow it, etc. Counting on you to do it!

It's all yours, run with it!
