### ISSUE TITLE
Put www.ruby-grape.org under SSL

### ISSUE THREAD

**Issue by dblock** [ruby-grape/ruby-grape.github.io#47]

**Comment by duffn** [comment]
This can be done easily and free with Cloudflare. https://medium.com/@samdutton/github-pages-cloudflare-custom-domain-checklist-e86c786194a4

**Comment by dblock** [comment]
GitHub pages does this automatically. I checked a box in the configuration and redeployed. Check out https://www.ruby-grape.org/.

**Comment by duffn** [comment]
Nice.
