### ISSUE TITLE
Add some history of grape, give credit to Jerry, Michael, dB.

### ISSUE THREAD

**Issue by dblock** [ruby-grape/ruby-grape.github.io#5]
See https://github.com/ruby-grape/grape/blob/gh-pages/index.html. We want a history page that says that @mbleigh created Grape, Jerry worked on it and dB. took over as a maintainer. And that the organization was born on August 3rd, 2015.

**Comment by mbleigh** [comment]
Not to be too pedantic but I created it and Jerry worked on it :smile:

**Comment by mbleigh** [comment]
The first official debut of Grape was at RubyConf 2010 in [this talk](http://confreaks.tv/videos/rubyconf2010-the-grapes-of-rapid)

**Comment by dblock** [comment]
Please edit http://ruby-grape.github.io/team.
